include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  errors:
    file_names: error
    omit_local_variable_types: ignore
    #prefer_relative_imports: error

  exclude:
    - lib/services/getIt.dart

linter:
  rules:
    file_names: true
    #prefer_relative_imports: true